/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class src_media_VolumeControl */

#ifndef _Included_src_media_VolumeControl
#define _Included_src_media_VolumeControl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     src_media_VolumeControl
 * Method:    SetVolumeValue
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_src_media_VolumeControl_SetVolumeValue
  (JNIEnv *, jobject, jlong);

/*
 * Class:     src_media_VolumeControl
 * Method:    GetVolumeValue
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_src_media_VolumeControl_GetVolumeValue
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
